[package]
name = "wpp-wasm-runtime"
version = "0.1.0"
edition = "2021"



[dependencies]
wasm-bindgen = "0.2"
wasm-encoder = "0.24.1"


[dependencies.web-sys]
version = "0.3"
features = ["CanvasRenderingContext2d", "HtmlCanvasElement", "Document", "Window"]
